# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Training Course in Galaxy for Metagenomic Analysis on Targeted and Whole Genome Sequencing Data
tagline:             IZS3
description:         Training Course on Galaxy for Istituto Zooprofilattico Sperimentale della Sardegna
url:                 'https://next-crs4.github.io/galaxy-training_izs3'
baseurl:             ''
twitter_username:
github_username:  crs4
pages_url: https://github.com/next-crs4/galaxy-training-izs3
github_url: https://github.com/next-crs4/galaxy-training-izs3

# Custom vars
version:             23.03

# Build settings
markdown: kramdown
